const avaliablNeighborhood = [
  "Aflitos",
  "Apipucos",
  "Barro",
  "Boa Viagem",
  "Boa Vista",
  "Campo Grande",
  "Casa Amarela",
  "Casa Forte",
  "Caxangá",
  "Cidade Universitária",
  "Cordeiro",
  "Curado",
  "Derby",
  "Encruzilhada",
  "Espinheiro",
  "Estância",
  "Graças",
  "Ilha do Leite",
  "Ilha do Retiro",
  "Imbiribeira",
  "Iputinga",
  "Jaqueira",
  "Macaxeira",
  "Madalena",
  "Monteiro",
  "Paissandu",
  "Parnamirim",
  "Pina",
  "Poço da Panela",
  "Prado",
  "Santo Amaro",
  "Tamarineira",
  "Tejipió",
  "Torre",
  "Torreão",
  "Zumbi"
];

module.exports = { avaliablNeighborhood };
